apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.basicDeploy.serviceType1.name }}
  labels:
    subproject: {{ .Values.basicDeploy.name }}
spec:
  selector:
    app: {{ .Values.basicDeploy.deploymentType1.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.basicDeploy.serviceType1.servicePort }}
      targetPort: {{ .Values.basicDeploy.deploymentType1.containerPort }}
  type: {{ .Values.basicDeploy.serviceType1.type }}
