apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: a-{{ randAlphaNum 8 | lower }}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.basicDeploy.serviceType1.name }}
                port:
                  number: {{ .Values.basicDeploy.serviceType1.servicePort }}
    - host: b-{{ randAlphaNum 8 | lower }}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.basicDeploy.serviceType2.name }}
                port:
                  number: {{ .Values.basicDeploy.serviceType2.servicePort }}
    - host: vm-{{ randAlphaNum 8 | lower }}.example.com
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.kubevirt.virtualMachineService.name }}
                port:
                  number: 80
