apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .Values.kubevirt.dataVolumeExtra.name }}
spec:
  source:
    pvc:
      name: {{ .Values.kubevirt.dataVolumeExtra.pvc.name }}
      namespace: {{ .Values.kubevirt.dataVolumeExtra.pvc.namespace | default .Release.Namespace }}
  storage:
    storageClassName: {{ .Values.kubevirt.dataVolumeExtra.storageClassName }}
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
