apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .Values.kubevirt.dataVolume.name }}
spec:
  source:
    registry:
      url: docker://docker.io/rrukmantiyo/kubevirt-images:ubuntu-22.04
  storage:
    storageClassName: {{ .Values.kubevirt.dataVolume.storageClassName }}
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
