apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.kubevirt.dataVolumeExtra.pvc.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.kubevirt.dataVolumeExtra.storageClassName }}
