apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jobs.monitorJob.serviceAccount.name }}
  namespace: {{ .Values.jobs.monitorJob.serviceAccount.namespace | default .Release.Namespace }}
