apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.jobs.monitorJob.roleBinding.name }}
  namespace: {{ .Values.jobs.monitorJob.roleBinding.namespace | default .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.jobs.monitorJob.serviceAccount.name }}
    namespace: {{ .Values.jobs.monitorJob.serviceAccount.namespace | default .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.jobs.monitorJob.role.name }}
  apiGroup: rbac.authorization.k8s.io
